# Generated by Django 3.2.13 on 2022-06-17 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_expires', models.CharField(blank=True, max_length=5, null=True)),
                ('notifications', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('is_client', models.BooleanField(blank=True, null=True)),
                ('is_merchant', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
