# Generated by Django 3.2.13 on 2022-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
